app:
  back_port: 2079
  data_dir: data

pocket:
  token: <token>
  app_info: '{"vendor":"apple","deviceId":"F9751B64-E90D-62EA-6303-F278CE6AFE27","appVersion":"7.1.12","appBuild":"24061501","osVersion":"17.1.1","osType":"ios","deviceName":"iPhone 12 mini","os":"ios"}'
  pa: <pa>
  interval: 500

aai:
  token: <token>

medium:
  token: <token>
