app:
  back_port: 2079
  data_dir: data

pocket:
  token: <token>
  interval: 500
  app_info:
    vendor: apple
    deviceId:
    appVersion: 7.1.12
    appBuild: 24061501
    osVersion: 17.1.1
    osType: ios
    deviceName: iPhone 12 mini
    os: ios

aai:
  token: <token>
