name: Build and Push Frontend to Docker Hub

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - 'front/**'
      - '.github/workflows/build-front.yaml'
  push:
    branches:
      - main
    paths:
      - 'front/**'
      - '.github/workflows/build-front.yaml'
  workflow_dispatch:

jobs:
  build-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "TAG=${{ secrets.DOCKERHUB_USERNAME }}/liveguard-front:pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ secrets.DOCKERHUB_USERNAME }}/liveguard-front:latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ env.TAG }}

  tag-latest:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-front

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull PR image and tag as latest
        run: |
          PR_NUMBER=$(gh pr list --state merged --limit 1 --json number --jq '.[0].number')
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/liveguard-front
          docker pull $IMAGE:pr-$PR_NUMBER
          docker tag $IMAGE:pr-$PR_NUMBER $IMAGE:latest
          docker push $IMAGE:latest
